# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  symlinks:
    security_baseline: "#{source_dir}"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.0.0"
    kmod:
      repo: "camptocamp/kmod"
      ref: "2.3.1"
    augeas:
      repo: "camptocamp/augeas"
      ref: "1.8.0"
